services:
  db:
    image: mysql:8.0
    container_name: db_cont
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - notes-app-nw

  django_app:
    image: notes-app:latest
    pull_policy: never
    container_name: django_cont
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - notes-app-nw

  nginx:
    image: nginx:latest
    container_name: nginx_cont
    ports:
      - "8888:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - django_app
    restart: always
    networks:
      - notes-app-nw

volumes:
  mysql_data:

networks:
  notes-app-nw:
