services:
  nginx:
    image: nginx:latest
    container_name: nginx_cont
    ports:
      - "8888:80"
    restart: always
    depends_on:
      - django_app
    networks:
      - notes-app-nw

  django_app:
    image: notes-app:latest
    pull_policy: never
    container_name: django_cont
    command: >
      sh -c "
      sleep 30 &&
      python manage.py migrate --noinput &&
      gunicorn notesapp.wsgi --bind 0.0.0.0:8000
      "
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - notes-app-nw

  db:
    image: mysql:8
    container_name: db_cont
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 90s
    restart: always
    networks:
      - notes-app-nw

volumes:
  mysql_data:

networks:
  notes-app-nw:
