version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: db_cont
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always
    networks:
      - notes-app-nw

  django_app:
    image: notes-app:latest
    pull_policy: never
    container_name: django_cont
    command: >
      sh -c "
      echo 'Waiting for MySQL...' &&
      until mysqladmin ping -h db -uroot -proot --silent; do
        sleep 3;
      done &&
      echo 'MySQL is ready' &&
      python manage.py migrate --noinput &&
      gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000
      "
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - notes-app-nw

  nginx:
    image: nginx:latest
    container_name: nginx_cont
    ports:
      - "8888:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - django_app
    restart: always
    networks:
      - notes-app-nw

volumes:
  mysql_data:

networks:
  notes-app-nw:
